name: patch release

on:
  push:
    branches: [main]
  pull_request:
    paths:
      - .github/workflows/release-patch.yml
      - .github/workflows/patch-release-reusable.yml
  workflow_dispatch:
    inputs:
      dry-run:
        description: Dry run
        type: boolean
        default: true

concurrency:
  group: patch-release
  cancel-in-progress: false

jobs:
  release:
    if: github.event_name != 'pull_request' && github.actor != 'github-actions[bot]'
    uses: ./.github/workflows/patch-release-reusable.yml
    with:
      dry-run: ${{ github.event_name == 'workflow_dispatch' && inputs.dry-run || false }}
      commit-version-bump: ${{ github.event_name == 'push' }}
    permissions:
      contents: write
      id-token: write

  dry-run:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/patch-release-reusable.yml
    with:
      dry-run: true
    permissions:
      contents: read
